development:
  pool: 5
  encoding: unicode
  adapter: postgresql
  database: Finance_development
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  pool: 5
  encoding: unicode
  adapter: postgresql
  database: Finance_production
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
